# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tony's Thoughts
description: >- # this means to ignore newlines until "baseurl:"
  My personal blog where any given day I will attempt to
  convert the thoughts flowing through my mind into text.

  It has been four years since I have blogged so
  enjoy the old material, which I also now laugh at,
  and feel free to critique anything that I write.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hat.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ttys001
linkedin_username: tony-hendrick
github_username:  hat

# JEKYLL SETTINGS
excerpt_separator: <!--more-->

# Avatar img
avatar_pic: /assets/avatar_img.png

# Build settings
theme: minima
plugins:
  - jekyll-feed

color_pallete: https://coolors.co/b24c63-bf8eff-5438dc-8fe388

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
